spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/trip-reco
#    url: jdbc:h2:mem:tripreco;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
#    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

jwt:
  expiration_time: 3600000 # 1시간
  secret: 7KeR7JeQ7ISc7ZWY64qUIOyKpO2UhOungeu2gO2KuOuekSBqcGHrnpEg7Iuc7YGQ66as7YuwIOyYiOygnA==

openai:
  api:
    key: sk-
  base-url: https://api.openai.com/v1