spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true # 쿼리를 한 줄이 아닌 예쁘게 줄바꿈해서 출력
        highlight_sql: true # 터미널에서 가독성을 위해 추천
        use_sql_comments: true # 어떤 메서드 때문에 발생한 쿼리인지 주석 추가
        default_batch_fetch_size: 100
        dialect: ${SPRING_DATASOURCE_DIALECT}
  #    open-in-view: false

  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  access_expiration_time: 300_000 # 5분 1000 * 60 * 5
  refresh_expiration_time: 604_800_000 # 일주일 1000 * 60 * 60 * 24 * 7
  guest_token_exp_time: 3600000 # 1시간 1000 * 60 * 60
  secret: 7KeR7JeQ7ISc7ZWY64qUIOyKpO2UhOungeu2gO2KuOuekSBqcGHrnpEg7Iuc7YGQ66as7YuwIOyYiOygnA==

openai:
  api:
    key: ${OPENAI_API_KEY}
    model: gpt-4o-mini
  base-url: https://api.openai.com/v1